name: OSM2GTFS for Addis Ababa

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout AddisMapTransit-gtfs
      uses: actions/checkout@v3        
    - name: Checkout osm2gtfs
      uses: actions/checkout@v3
      with:
        repository: AddisMap/osm2gtfs
        ref: refs/heads/master 
        path: osm2gtfs       
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        cd osm2gtfs
        pip install -e .
    - name: Run
      run: |
        cd osm2gtfs      
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config.json --refresh-all 2>&1 | tee ../generation.log      
        cp data/et-addisababa.zip ../
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config_bus.json --refresh-all 2>&1 | tee ../generation-bus.log
        cp data/et-addisababa-bus.zip ../
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config_bus_AB.json --refresh-all 2>&1 | tee ../generation-bus-ab.log
        cp data/et-addisababa-bus-ab.zip ../
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config_bus_SH.json --refresh-all 2>&1 | tee ../generation-bus-sh.log
        cp data/et-addisababa-bus-sh.zip ../        
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config_minibus.json --refresh-all 2>&1 | tee ../generation-minibus.log
        cp data/et-addisababa-minibus.zip ../        
        cd ../
        rm -r osm2gtfs
        unzip -o et-addisababa.zip        
        ls -al
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

        
