name: OSM2GTFS for Addis Ababa

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout osm2gtfs repo
      uses: actions/checkout@v3
      with:
        repository: AddisMap/osm2gtfs
        ref: refs/heads/develop-flex-python3  
        path: osm2gtfs 
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        cd osm2gtfs
        pip install -e .
    - name: Run
      run: |
        cd osm2gtfs      
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config.json --refresh-all 2>&1 | tee ..//generation.log
        cp data/et-addisababa.zip ../
        cd ../
        rm -r osm2gtfs
        unzip et-addisababa.zip
        rm et-addisababa.zip
        find
