name: OSM2GTFS for Addis Ababa

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        name: AddisMap/osm2gtfs
        ref: refs/heads/develop-flex   
    - name: Set up Python 2
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e
    - name: Run
      run: |
        osm2gtfs -c osm2gtfs/creators/et_addisababa/config.json --refresh-all 2>&1 | tee generation.log
    
